### PR TITLE
[TASK] Updates dependencies: TYPO3 core ^12.4, bootstrap ^14

### PR DESCRIPTION
**Pull request by garvinhicking**
(Currently referenced TYPO3 core versions have a few bugs, as well as the boostrap package, which may confuse new users of TYPO3 due to site-breaking issues: any content element with an RTE cannot be edited in the backend)

I am unsure if `main` is the proper current branch, or if it should be `v12-0`? Happy to adjust my PR if so.

### CODE REVIEW

**Comment by DavidBruchmann** [comment]
Thanks, looks good (I didn't test though).
I'm not in the documentation team anymore, so I can't merge.
Perhaps @brotkrueml could have a look?

**Comment by brotkrueml** [comment]
@garvinhicking Thanks for your contribution. I would like to wait until #38 and #39 are merged. After that, please merge the main branch into your PR - so we can check, if the tests are green again.

**Comment by fe-hicking** [comment]
Sure thing, I'll wait. It would be great if you can just ping me when I shall update the PR. Thanks for your work!

**Comment by brotkrueml** [comment]
@garvinhicking ping :-)

**Comment by garvinhicking** [comment]
Updated my main, so this PR should apply properly and be tested now? @brotkrueml

**Comment by brotkrueml** [comment]
@garvinhicking Thank you. Looks good.

**Review by brotkrueml — APPROVED** [review]

**Pull request merged**
